USE [master]
GO

/****** Object:  Database [DB_PRUEBA]    Script Date: 4/1/2023 3:43:29 PM ******/
CREATE DATABASE [DB_PRUEBA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_TEST', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DB_TEST.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_TEST_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DB_TEST_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_PRUEBA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_PRUEBA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_PRUEBA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_PRUEBA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_PRUEBA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_PRUEBA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_PRUEBA] SET  MULTI_USER 
GO

ALTER DATABASE [DB_PRUEBA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_PRUEBA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_PRUEBA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_PRUEBA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_PRUEBA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_PRUEBA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_PRUEBA] SET  READ_WRITE 
GO

